name = "kadad-bale"
main = "worker.js"
compatibility_date = "2026-09-27"

[ai]
binding = "AI"

[vars]
ADMIN_USERNAME = "kavandad"

[[d1_databases]]
binding = "DB"
database_name = "kadad-bale"
database_id = "35193f03-2c21-4a9b-807a-3b7d77749af6"
